/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */

export interface ActionLogResponseDto {
  id?: number;
  /** @nullable */
  username?: string | null;
  timestamp?: string;
  /** @nullable */
  action?: string | null;
}
