/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */

export interface ChangePasswordDto {
  /** @minLength 1 */
  currentPassword: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string;
  /** @minLength 1 */
  confirmNewPassword: string;
}
