/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */

export interface CreateTodoDto {
  /**
   * @minLength 1
   * @maxLength 500
   */
  text: string;
}
