/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */

export interface LoginDto {
  /** @minLength 1 */
  usernameOrEmail: string;
  /** @minLength 1 */
  password: string;
}
