/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */

export interface RegisterDto {
  /**
   * @minLength 3
   * @maxLength 100
   */
  username: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  email: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /** @minLength 1 */
  confirmPassword: string;
}
