/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */
import type { TodoStatus } from './todoStatus';

export interface TodoResponseDto {
  id?: number;
  /** @nullable */
  text?: string | null;
  status?: TodoStatus;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  completedAt?: string | null;
}
