/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */

export type TodoStatus = (typeof TodoStatus)[keyof typeof TodoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TodoStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
