/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NullableOfTodoStatus } from './nullableOfTodoStatus';

export interface UpdateTodoDto {
  /**
   * @minLength 1
   * @maxLength 500
   * @nullable
   */
  text?: string | null;
  status?: NullableOfTodoStatus;
}
