/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import type { DeepNonNullable } from '@orval/core';

import { Observable } from 'rxjs';

import type {
  ActionLogsResponseDto,
  GetAllActionLogsParams,
  GetUserActionLogsParams,
} from '../todoApi.schemas';

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | ReadonlyArray<string | number | boolean>
      >;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: { includeHeaders?: string[] } | boolean;
  timeout?: number;
}

@Injectable({ providedIn: 'root' })
export class ActionLogsService {
  private readonly http = inject(HttpClient);
  getUserActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetUserActionLogsParams>,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getUserActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetUserActionLogsParams>,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getUserActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetUserActionLogsParams>,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getUserActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetUserActionLogsParams>,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.get<TData>(`/api/action_logs`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  }
  getAllActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetAllActionLogsParams>,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getAllActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetAllActionLogsParams>,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getAllActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetAllActionLogsParams>,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getAllActionLogs<TData = ActionLogsResponseDto>(
    params?: DeepNonNullable<GetAllActionLogsParams>,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.get<TData>(`/api/action_logs/all`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  }
}

export type GetUserActionLogsClientResult = NonNullable<ActionLogsResponseDto>;
export type GetAllActionLogsClientResult = NonNullable<ActionLogsResponseDto>;
