/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ActionLogResponseDto {
  id?: number;
  username?: string;
  timestamp?: string;
  action?: string;
}
