/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordDto {
  currentPassword: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string;
  confirmNewPassword: string;
}
