/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TodoStatus } from './todoStatus';

export interface TodoResponseDto {
  id?: number;
  text?: string;
  status?: TodoStatus;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  completedAt?: string | null;
}
