/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type {
  AuthResponseDto,
  ChangePasswordDto,
  LoginDto,
  RegisterDto,
  ResetPasswordDto,
} from '../todoApi.schemas';

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | ReadonlyArray<string | number | boolean>
      >;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: { includeHeaders?: string[] } | boolean;
  timeout?: number;
}

@Injectable({ providedIn: 'root' })
export class AuthService {
  private readonly http = inject(HttpClient);
  postApiAuthRegister<TData = AuthResponseDto>(
    registerDto: RegisterDto,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  postApiAuthRegister<TData = AuthResponseDto>(
    registerDto: RegisterDto,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  postApiAuthRegister<TData = AuthResponseDto>(
    registerDto: RegisterDto,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  postApiAuthRegister<TData = AuthResponseDto>(
    registerDto: RegisterDto,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.post<TData>(`/api/Auth/register`, registerDto, options);
  }
  postApiAuthLogin<TData = AuthResponseDto>(
    loginDto: LoginDto,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  postApiAuthLogin<TData = AuthResponseDto>(
    loginDto: LoginDto,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  postApiAuthLogin<TData = AuthResponseDto>(
    loginDto: LoginDto,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  postApiAuthLogin<TData = AuthResponseDto>(
    loginDto: LoginDto,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.post<TData>(`/api/Auth/login`, loginDto, options);
  }
  postApiAuthChangePassword<TData = null>(
    changePasswordDto: ChangePasswordDto,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  postApiAuthChangePassword<TData = null>(
    changePasswordDto: ChangePasswordDto,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  postApiAuthChangePassword<TData = null>(
    changePasswordDto: ChangePasswordDto,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  postApiAuthChangePassword<TData = null>(
    changePasswordDto: ChangePasswordDto,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.post<TData>(
      `/api/Auth/change-password`,
      changePasswordDto,
      options,
    );
  }
  postApiAuthResetPassword<TData = null>(
    resetPasswordDto: ResetPasswordDto,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  postApiAuthResetPassword<TData = null>(
    resetPasswordDto: ResetPasswordDto,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  postApiAuthResetPassword<TData = null>(
    resetPasswordDto: ResetPasswordDto,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  postApiAuthResetPassword<TData = null>(
    resetPasswordDto: ResetPasswordDto,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.post<TData>(
      `/api/Auth/reset-password`,
      resetPasswordDto,
      options,
    );
  }
  postApiAuthLogout<TData = null>(
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  postApiAuthLogout<TData = null>(
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  postApiAuthLogout<TData = null>(
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  postApiAuthLogout<TData = null>(
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.post<TData>(`/api/Auth/logout`, undefined, options);
  }
  getApiAuthProfile<TData = null>(
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getApiAuthProfile<TData = null>(
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getApiAuthProfile<TData = null>(
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getApiAuthProfile<TData = null>(
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.get<TData>(`/api/Auth/profile`, options);
  }
}

export type PostApiAuthRegisterClientResult = NonNullable<AuthResponseDto>;
export type PostApiAuthLoginClientResult = NonNullable<AuthResponseDto>;
export type PostApiAuthChangePasswordClientResult = never;
export type PostApiAuthResetPasswordClientResult = never;
export type PostApiAuthLogoutClientResult = never;
export type GetApiAuthProfileClientResult = never;
