/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { TodoStatus } from '../todoApi.schemas';
import type { TodoResponseDto } from '../todoApi.schemas';

export const getGetTodosResponseMock = () =>
  (() => {
    return Array.from({ length: 10 }, () => ({
      id: faker.number.int({ min: 1, max: 100 }),
      text: faker.lorem.sentence(),
      createdAt: faker.date.past(),
      status: faker.number.int({ min: 0, max: 2 }),
      completedAt: void 0,
    }));
  })();

export const getCreateTodoResponseMock = (
  overrideResponse: Partial<TodoResponseDto> = {},
): TodoResponseDto => ({
  id: faker.number.int({ min: 0, max: 2147483647 }),
  text: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TodoStatus)),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  completed_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetTodoByIdResponseMock = (
  overrideResponse: Partial<TodoResponseDto> = {},
): TodoResponseDto => ({
  id: faker.number.int({ min: 0, max: 2147483647 }),
  text: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TodoStatus)),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  completed_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getUpdateTodoResponseMock = (
  overrideResponse: Partial<TodoResponseDto> = {},
): TodoResponseDto => ({
  id: faker.number.int({ min: 0, max: 2147483647 }),
  text: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TodoStatus)),
    undefined,
  ]),
  created_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  updated_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  completed_at: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetTodosMockHandler = (
  overrideResponse?:
    | TodoResponseDto[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<TodoResponseDto[]> | TodoResponseDto[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/todos',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetTodosResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateTodoMockHandler = (
  overrideResponse?:
    | TodoResponseDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<TodoResponseDto> | TodoResponseDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/todos',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateTodoResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetTodoByIdMockHandler = (
  overrideResponse?:
    | TodoResponseDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<TodoResponseDto> | TodoResponseDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/todos/:id',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetTodoByIdResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateTodoMockHandler = (
  overrideResponse?:
    | TodoResponseDto
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<TodoResponseDto> | TodoResponseDto),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/todos/:id',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateTodoResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getDeleteTodoMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/api/todos/:id',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getDeleteMultipleTodosMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/api/todos/bulk',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getUpdateMultipleTodoStatusMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/todos/bulk-status',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getTodosMock = () => [
  getGetTodosMockHandler(),
  getCreateTodoMockHandler(),
  getGetTodoByIdMockHandler(),
  getUpdateTodoMockHandler(),
  getDeleteTodoMockHandler(),
  getDeleteMultipleTodosMockHandler(),
  getUpdateMultipleTodoStatusMockHandler(),
];
