/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi
 * OpenAPI spec version: v1
 */
export interface ActionLogResponseDto {
  id?: number;
  /** @nullable */
  username?: string | null;
  timestamp?: string;
  /** @nullable */
  action?: string | null;
}

export interface AuthResponseDto {
  /** @nullable */
  token?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
  expires?: string;
}

export interface ChangePasswordDto {
  /** @minLength 1 */
  currentPassword: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string;
  /** @minLength 1 */
  confirmNewPassword: string;
}

export interface CreateTodoDto {
  /**
   * @minLength 1
   * @maxLength 500
   */
  text: string;
}

export interface DeleteMultipleTodosDto {
  /** @minItems 1 */
  todoIds: number[];
}

export interface LoginDto {
  /** @minLength 1 */
  usernameOrEmail: string;
  /** @minLength 1 */
  password: string;
}

export interface RegisterDto {
  /**
   * @minLength 3
   * @maxLength 100
   */
  username: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  email: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /** @minLength 1 */
  confirmPassword: string;
}

export interface ResetPasswordDto {
  /** @minLength 1 */
  email: string;
}

export interface TodoResponseDto {
  id?: number;
  /** @nullable */
  text?: string | null;
  status?: TodoStatus;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  completedAt?: string | null;
}

export type TodoStatus = (typeof TodoStatus)[keyof typeof TodoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TodoStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface UpdateTodoDto {
  /**
   * @minLength 1
   * @maxLength 500
   * @nullable
   */
  text?: string | null;
  status?: TodoStatus;
}
