/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { ActionLogResponseDto } from '.././model';

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | ReadonlyArray<string | number | boolean>
      >;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: { includeHeaders?: string[] } | boolean;
  timeout?: number;
}

@Injectable({ providedIn: 'root' })
export class ActionLogsService {
  private readonly http = inject(HttpClient);
  getApiActionLogs<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getApiActionLogs<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getApiActionLogs<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getApiActionLogs<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.get<TData>(`/api/ActionLogs`, options);
  }
  getApiActionLogsAll<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getApiActionLogsAll<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getApiActionLogsAll<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getApiActionLogsAll<TData = ActionLogResponseDto[]>(
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.get<TData>(`/api/ActionLogs/all`, options);
  }
}

export type GetApiActionLogsClientResult = NonNullable<ActionLogResponseDto[]>;
export type GetApiActionLogsAllClientResult = NonNullable<
  ActionLogResponseDto[]
>;
