/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * TodoApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type {
  CreateTodoDto,
  DeleteMultipleTodosDto,
  TodoResponseDto,
  UpdateTodoDto,
} from '.././model';

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | ReadonlyArray<string | number | boolean>
      >;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: { includeHeaders?: string[] } | boolean;
  timeout?: number;
}

@Injectable({ providedIn: 'root' })
export class TodosService {
  private readonly http = inject(HttpClient);
  getApiTodos<TData = TodoResponseDto[]>(
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getApiTodos<TData = TodoResponseDto[]>(
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getApiTodos<TData = TodoResponseDto[]>(
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getApiTodos<TData = TodoResponseDto[]>(
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.get<TData>(`/api/Todos`, options);
  }
  postApiTodos<TData = TodoResponseDto>(
    createTodoDto: CreateTodoDto,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  postApiTodos<TData = TodoResponseDto>(
    createTodoDto: CreateTodoDto,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  postApiTodos<TData = TodoResponseDto>(
    createTodoDto: CreateTodoDto,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  postApiTodos<TData = TodoResponseDto>(
    createTodoDto: CreateTodoDto,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.post<TData>(`/api/Todos`, createTodoDto, options);
  }
  getApiTodosId<TData = TodoResponseDto>(
    id: number,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getApiTodosId<TData = TodoResponseDto>(
    id: number,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getApiTodosId<TData = TodoResponseDto>(
    id: number,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getApiTodosId<TData = TodoResponseDto>(
    id: number,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.get<TData>(`/api/Todos/${id}`, options);
  }
  putApiTodosId<TData = TodoResponseDto>(
    id: number,
    updateTodoDto: UpdateTodoDto,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  putApiTodosId<TData = TodoResponseDto>(
    id: number,
    updateTodoDto: UpdateTodoDto,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  putApiTodosId<TData = TodoResponseDto>(
    id: number,
    updateTodoDto: UpdateTodoDto,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  putApiTodosId<TData = TodoResponseDto>(
    id: number,
    updateTodoDto: UpdateTodoDto,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.put<TData>(`/api/Todos/${id}`, updateTodoDto, options);
  }
  deleteApiTodosId<TData = null>(
    id: number,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  deleteApiTodosId<TData = null>(
    id: number,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  deleteApiTodosId<TData = null>(
    id: number,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  deleteApiTodosId<TData = null>(
    id: number,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.delete<TData>(`/api/Todos/${id}`, options);
  }
  deleteApiTodosBulk<TData = null>(
    deleteMultipleTodosDto: DeleteMultipleTodosDto,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  deleteApiTodosBulk<TData = null>(
    deleteMultipleTodosDto: DeleteMultipleTodosDto,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  deleteApiTodosBulk<TData = null>(
    deleteMultipleTodosDto: DeleteMultipleTodosDto,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  deleteApiTodosBulk<TData = null>(
    deleteMultipleTodosDto: DeleteMultipleTodosDto,
    options?: HttpClientOptions & { observe?: any },
  ): Observable<any> {
    return this.http.delete<TData>(`/api/Todos/bulk`, {
      body: deleteMultipleTodosDto,
      ...options,
    });
  }
}

export type GetApiTodosClientResult = NonNullable<TodoResponseDto[]>;
export type PostApiTodosClientResult = NonNullable<TodoResponseDto>;
export type GetApiTodosIdClientResult = NonNullable<TodoResponseDto>;
export type PutApiTodosIdClientResult = NonNullable<TodoResponseDto>;
export type DeleteApiTodosIdClientResult = never;
export type DeleteApiTodosBulkClientResult = never;
